from enum import Enum


class NistTestType(Enum):
    TEST_FREQUENCY = 1
    TEST_BLOCK_FREQUENCY = 2
    TEST_CUSUM = 3
    TEST_RUNS = 4
    TEST_LONGEST_RUN = 5
    TEST_RANK = 6
    TEST_FFT = 7
    TEST_NONPERIODIC = 8
    TEST_OVERLAPPING = 9
    TEST_UNIVERSAL = 10
    TEST_APEN = 11
    TEST_RND_EXCURSION = 12
    TEST_RND_EXCURSION_VAR = 13
    TEST_SERIAL = 14
    TEST_LINEARCOMPLEXITY = 15
