START TRANSACTION;
/* INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (2,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(3,10000,1,1,NULL);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(4,10000,3,1, NULL);
*/
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(3,10000,1,NULL,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(4,10000,2,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(5,10000,3,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(6,10000,4,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(7,10000,5,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(8,10000,6,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(9,10000,7,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(10,10000,8,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(11,10000,9,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(12,10000,10,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(13,10000,11,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(14,10000,12,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(15,10000,13,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(16,10000,14,1,NULL);
INSERT INTO tests (id_file, id_user, test_table, loaded, ended) VALUES (1,1,"nist",0,0);
INSERT INTO nist_tests (id_test, length, test_number, streams, special_parameter) VALUES(17,10000,15,1,NULL);
COMMIT;
